# Generated by Django 4.0.5 on 2022-06-19 07:52

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Neighbourhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/dz275mqsc/image/upload/v1654858776/default_nbsolf.png', max_length=255, verbose_name='image')),
                ('name', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('health_dept', phone_field.models.PhoneField(blank=True, help_text='Phone Number Format: +254712345678', max_length=20, unique=True)),
                ('police_dept', phone_field.models.PhoneField(blank=True, help_text='Phone Number Format: +254712345678', max_length=20, unique=True)),
                ('occupants', models.IntegerField(null=True, verbose_name='Occupants')),
                ('date', models.DateField(auto_now_add=True)),
                ('admin', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dz275mqsc/image/upload/v1654858776/default_nbsolf.png', max_length=255, verbose_name='image')),
                ('bio', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=20)),
                ('location', models.CharField(blank=True, max_length=20, null=True)),
                ('neighbourhood', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pple', to='app.neighbourhood')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/december/image/upload/v1655623355/hood/tree_lhfavv.jpg', max_length=255, verbose_name='image')),
                ('title', models.CharField(max_length=20)),
                ('context', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('neighbourhood', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.neighbourhood')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/december/image/upload/v1655623268/hood/business_tny1aq.jpg', max_length=255, verbose_name='image')),
                ('title', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('neighbourhood', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.neighbourhood')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
