# Generated by Django 4.0.5 on 2022-06-18 01:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_alter_neighbourhood_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='health_dept',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Phone Number Format: +254712345678', max_length=20, region=None, unique=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='occupants',
            field=models.IntegerField(null=True, verbose_name='Occupants'),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='police_dept',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Phone Number Format: +254712345678', max_length=20, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='neighbourhood',
            name='admin',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='occupant',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
