# Generated by Django 4.0.5 on 2022-06-19 08:15

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/december/image/upload/v1655623268/hood/business_tny1aq.jpg', max_length=255, null=True, verbose_name='image'),
        ),
    ]
