# Generated by Django 4.0.5 on 2022-06-19 08:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_business_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
