# Generated by Django 4.0.5 on 2022-06-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_post_context_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbourhood',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
