# Generated by Django 4.0.5 on 2022-06-18 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_neighbourhood_image_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighbourhood',
            name='image',
        ),
    ]
