# Generated by Django 4.0.5 on 2022-06-18 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_neighbourhood_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_pic',
        ),
    ]
