# Generated by Django 4.0.5 on 2022-06-18 09:40

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_neighbourhood_image_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbourhood',
            name='admin',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='app.profile'),
        ),
        migrations.AlterField(
            model_name='neighbourhood',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
