# Generated by Django 4.0.5 on 2022-06-18 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_neighbourhood_admin_alter_neighbourhood_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='neighbourhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pple', to='app.neighbourhood'),
        ),
    ]
